# Ex1 - Filtering and Sorting Data

## Learning Objectives
In this exercise, you will learn:
- How to filter data based on conditions
- How to sort data in pandas
- How to work with string data types
- Different methods to count and aggregate data
- Multiple approaches to solve the same problem

### Step 1. Import the necessary libraries

**Explanation:**  
We import two essential libraries for data analysis:

- **`pandas`**: The primary library for data manipulation and analysis in Python
- **`numpy`**: Provides support for numerical operations and arrays

**Convention:**  
- `pd` is the standard alias for pandas
- `np` is the standard alias for numpy

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv)

**Explanation:**  
`pd.read_csv()` can read data directly from a URL. In this case, we're loading a TSV (Tab-Separated Values) file from GitHub.

**Key parameters:**
- **`sep="\t"`**: Specifies that the file uses tabs (`\t`) as separators instead of commas
  - TSV files use tabs, CSV files use commas
  - This tells pandas how to split the data into columns
- **`index_col="order_id"`**: Uses the 'order_id' column as the DataFrame index
  - This makes it easier to access rows by order ID
  - The order_id column will no longer be a regular data column

**What is a TSV file?**  
A TSV (Tab-Separated Values) file is similar to a CSV but uses tab characters instead of commas to separate values. This is useful when your data contains commas within the values themselves.

In [3]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep="\t", index_col="order_id")
chipo

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25


**Expected Output:**
```
          quantity                              item_name  \
order_id                                                    
1                1           Chips and Fresh Tomato Salsa   
1                1                                   Izze   
1                1                       Nantucket Nectar   
1                1  Chips and Tomatillo-Green Chili Salsa   
2                2                           Chicken Bowl   
...            ...                                    ...   
1833             1                          Steak Burrito   
1833             1                          Steak Burrito   
1834             1                     Chicken Salad Bowl   
1834             1                     Chicken Salad Bowl   
1834             1                     Chicken Salad Bowl   

                                         choice_description item_price  
order_id                                                                
1                                                       NaN     $2.39   
1                                              [Clementine]     $3.39   
1                                                   [Apple]     $3.39   
1                                                       NaN     $2.39   
2         [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                     ...        ...   
1833      [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
1833      [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 4 columns]
```

### Step 3. Display the first 10 rows

**Explanation:**  
`.head()` is a pandas method that displays the first rows of a DataFrame.

**Key points:**
- **Default behavior**: `.head()` with no argument shows the first **5 rows**
- **Custom amount**: `.head(10)` shows the first **10 rows**
- **Useful for**: Quickly inspecting your data structure and content

**Counterpart:** `.tail(n)` shows the last n rows

In [4]:
chipo.head(10)

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
3,1,Side of Chips,NaN,$1.69
4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25


**Expected Output:**
```
          quantity                              item_name  \
order_id                                                    
1                1           Chips and Fresh Tomato Salsa   
1                1                                   Izze   
1                1                       Nantucket Nectar   
1                1  Chips and Tomatillo-Green Chili Salsa   
2                2                           Chicken Bowl   
3                1                           Chicken Bowl   
3                1                              Side of Chips   
4                1                          Steak Burrito   
4                1                       Steak Soft Tacos   
5                1                          Steak Burrito   

                                         choice_description item_price  
order_id                                                                
1                                                       NaN     $2.39   
1                                              [Clementine]     $3.39   
1                                                   [Apple]     $3.39   
1                                                       NaN     $2.39   
2         [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
3         [[Fresh Tomato Salsa (Mild), [Rice, Cheese, So...    $10.98   
3                                                       NaN     $1.69   
4         [Tomatillo-Red Chili Salsa, [Fajita Vegetables...    $11.75   
4         [[Tomatillo-Green Chili Salsa (Medium), [Pinto...    $9.25   
5         [[Fresh Tomato Salsa (Mild), [Rice, Black Bean...    $9.25   
```

### Step 4. Get information about the DataFrame

**Explanation:**  
`.info()` provides a concise summary of the DataFrame structure.

**Information provided:**
- **Number of rows and columns**: Total dataset size
- **Column names**: List of all columns
- **Data types**: Type of data in each column (object, int64, float64, etc.)
- **Non-null counts**: How many non-missing values in each column
- **Memory usage**: How much memory the DataFrame consumes

**Useful for:**
- Identifying missing data (comparing Non-Null Count with total rows)
- Understanding data types (important for operations and conversions)
- Quick overview of dataset structure

In [5]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4622 entries, 1 to 1834
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   quantity            4622 non-null   int64 
 1   item_name           4622 non-null   object
 2   choice_description  3376 non-null   object
 3   item_price          4622 non-null   object
dtypes: int64(1), object(3)
memory usage: 180.5+ KB


**Expected Output:**
```
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4622 entries, 1 to 1834
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   quantity            4622 non-null   int64 
 1   item_name           4622 non-null   object
 2   choice_description  3376 non-null   object
 3   item_price          4622 non-null   object
dtypes: int64(1), object(3)
memory usage: 180.5+ KB
```

**Key observations:**
- 4622 total entries (orders)
- `choice_description` has 3376 non-null values (1246 missing values)
- `item_price` is stored as 'object' (string) because of the '$' symbol - we'll need to convert this later

### Step 5. Print the unique item names

**Explanation:**  
`.unique()` returns an array of all unique (distinct) values in a column.

**Key points:**
- Removes duplicates and shows only one instance of each value
- Returns a numpy array, not a pandas Series
- Order is not guaranteed (may not be alphabetical)

**Use cases:**
- Finding all unique categories
- Checking for data entry inconsistencies (e.g., "Burrito" vs "burrito")
- Understanding the variety in your dataset

In [6]:
chipo['item_name'].unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos

**Expected Output:**
```
array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos', 'Chicken Soft Tacos',
       'Chicken Burrito', 'Canned Soda', 'Barbacoa Burrito',
       'Carnitas Bowl', 'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl',
       'Steak Bowl', 'Barbacoa Soft Tacos', 'Veggie Burrito',
       'Carnitas Burrito', 'Veggie Bowl', 'Steak Crispy Tacos',
       'Chips and Tomatillo Red Chili Salsa', 'Barbacoa Crispy Tacos',
       'Veggie Salad Bowl', 'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       'Carnitas Crispy Tacos', '6 Pack Soft Drink', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad',
       'Barbacoa Salad', 'Bowl', 'Burrito', 'Crispy Tacos', 'Steak Salad'], dtype=object)
```

### Step 6. Count how many unique items are in the dataset - Method 1

**Explanation:**  
`.nunique()` counts the number of unique (distinct) values in a column.

**Difference from `.unique()`:**
- `.unique()` returns an **array of the actual values**
- `.nunique()` returns a **single number** (the count)

**Example:**
- If a column has values: ['A', 'B', 'A', 'C', 'B']
- `.unique()` returns: ['A', 'B', 'C']
- `.nunique()` returns: 3

In [7]:
chipo['item_name'].nunique()

50

**Expected Output:**
```
50
```

This means there are **50 different menu items** in the Chipotle dataset.

### Step 6 (Alternative). Count unique items - Method 2

**Explanation:**  
This is an **alternative approach** to count unique items by combining two methods:

1. **`.unique()`**: Gets the array of unique values
2. **`len()`**: Counts how many elements are in that array

**Comparison:**
- **Method 1** (above): `chipo['item_name'].nunique()` → Direct and efficient
- **Method 2** (this): `len(chipo['item_name'].unique())` → Two-step process

**Which is better?**  
`.nunique()` is **preferred** because:
- More readable and explicit
- Slightly more efficient (doesn't need to store the array in memory)
- Standard pandas convention

**When to use `len(.unique())`:**  
When you also need the actual unique values for other operations.

In [8]:
len(chipo['item_name'].unique())

50

**Expected Output:**
```
50
```

Same result as Method 1, confirming there are 50 unique items.

### Step 7. Convert item_price from string to float

**Explanation:**  
Currently, `item_price` is stored as a string (object type) because it includes the '$' symbol. We need to convert it to a numeric type to perform calculations.

**Breaking down the code:**

1. **`chipo['item_price'].apply(lambda x: x[1:])`**:
   - `.apply()` applies a function to each value in the column
   - `lambda x: x[1:]` is an anonymous function that:
     - Takes each value `x` (e.g., '$2.39')
     - Slices from index 1 onwards: `x[1:]` removes the first character '$'
     - Returns '2.39' (as a string)

2. **`.astype(float)`**:
   - Converts the string '2.39' to the float 2.39
   - Now we can perform mathematical operations

3. **Assignment**: Replaces the original column with the numeric version

**Why is this important?**  
Without this conversion, operations like `.max()`, `.sum()`, or `.mean()` won't work properly on price data.

In [9]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: x[1:]).astype(float)

**Verification:**  
Let's check the data type changed:

In [10]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4622 entries, 1 to 1834
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   quantity            4622 non-null   int64  
 1   item_name           4622 non-null   object 
 2   choice_description  3376 non-null   object 
 3   item_price          4622 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 180.5+ KB


**Note:** Now `item_price` shows as `float64` instead of `object`

### Step 8. Create a new column for unit price

**Explanation:**  
We're creating a new column `item_price_unit` that calculates the **price per individual item**.

**Formula:**  
`unit_price = total_price / quantity`

**Example:**
- If someone orders 2 burritos for $16.98
- `item_price` = 16.98 (total)
- `quantity` = 2
- `item_price_unit` = 16.98 / 2 = 8.49 (price per burrito)

**Key concept:**  
This is **vectorized operation** - pandas automatically divides each row's price by its quantity without needing a loop.

**Why is this useful?**  
Allows us to compare individual item prices across orders with different quantities.

In [11]:
chipo['item_price_unit'] = chipo['item_price'] / chipo['quantity']
chipo.head()

,quantity,item_name,choice_description,item_price,item_price_unit
order_id,,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,Izze,[Clementine],3.39,3.39
1,1,Nantucket Nectar,[Apple],3.39,3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49


**Expected Output (first 5 rows):**
```
          quantity                              item_name choice_description  \
order_id                                                                       
1                1           Chips and Fresh Tomato Salsa                NaN   
1                1                                   Izze       [Clementine]   
1                1                       Nantucket Nectar            [Apple]   
1                1  Chips and Tomatillo-Green Chili Salsa                NaN   
2                2                           Chicken Bowl  [Tomatillo-Red...   

          item_price  item_price_unit  
order_id                               
1              2.39             2.39  
1              3.39             3.39  
1              3.39             3.39  
1              2.39             2.39  
2             16.98             8.49  
```

### Step 9. Sort by item name

**Explanation:**  
`.sort_values()` sorts the DataFrame based on one or more columns.

**Parameters:**
- **`by='item_name'`**: The column to sort by

**Default behavior:**
- Sorts in **ascending order** (A to Z for strings, low to high for numbers)
- Returns a **new sorted DataFrame** (doesn't modify the original)

**Additional options:**
- `ascending=False` for descending order (Z to A, high to low)
- `inplace=True` to modify the original DataFrame instead of creating a copy
- Can sort by multiple columns: `by=['column1', 'column2']`

**Use case:**  
Organizing data alphabetically makes it easier to find specific items or identify patterns.

In [12]:
chipo.sort_values(by='item_name')

,quantity,item_name,choice_description,item_price,item_price_unit
order_id,,,,,
1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
749,1,6 Pack Soft Drink,[Coke],6.49,6.49
754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...
948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49


**Expected Output (showing first and last few rows):**
```
          quantity                item_name                     choice_description  \
order_id                                                                             
3389             1          6 Pack Soft Drink                          [Diet Coke]   
1849             1          6 Pack Soft Drink                              [Coke]   
...            ...                      ...                                    ...   
1112             1            Veggie Soft Tacos  [[Fresh Tomato Salsa, [Rice, ...   
1364             1            Veggie Soft Tacos  [[Roasted Chili Corn Salsa (Me...   

          item_price  item_price_unit  
order_id                               
3389           6.49             6.49  
1849           6.49             6.49  
...             ...              ...  
1112           8.75             8.75  
1364           8.49             8.49  

[4622 rows x 5 columns]
```

Notice the items are now alphabetically ordered from '6 Pack Soft Drink' to 'Veggie Soft Tacos'.

### Step 10. Find the most expensive item - Method 1 (using filtering)

**Explanation:**  
This approach uses **boolean indexing** to find the row with the maximum price.

**Breaking down the code:**

1. **`chipo['item_price'].max()`**:
   - Finds the maximum value in the `item_price` column
   - Returns a single number (e.g., 44.25)

2. **`chipo['item_price'] == chipo['item_price'].max()`**:
   - Creates a **boolean mask** (True/False for each row)
   - True where the price equals the maximum
   - False everywhere else

3. **`chipo[...]`**:
   - Filters the DataFrame using the boolean mask
   - Returns only rows where the condition is True

**Result:** The complete row(s) with the highest price

**Note:** If multiple rows have the same maximum price, all will be returned.

In [13]:
chipo[chipo['item_price'] == chipo['item_price'].max()]

,quantity,item_name,choice_description,item_price,item_price_unit
order_id,,,,,
1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95


**Expected Output:**
```
          quantity                     item_name choice_description  item_price  \
order_id                                                                          
1443            15  Chips and Fresh Tomato Salsa                NaN       44.25   

          item_price_unit  
order_id                   
1443                 2.95  
```

**Analysis:**  
The most expensive single order was 15 orders of Chips and Fresh Tomato Salsa for a total of $44.25 ($2.95 each).

### Step 10 (Alternative). Find most expensive item - Method 2 (using idxmax)

**Explanation:**  
`.idxmax()` returns the **index label** of the row with the maximum value.

**Breaking down the code:**

1. **`chipo['item_price'].idxmax()`**:
   - Finds which index has the maximum price
   - Returns the index label (in this case, order_id = 1443)
   - Does NOT return the price itself, just the index

2. **`.loc[...]`**:
   - Uses the index label to retrieve the entire row

**Comparison with Method 1:**
- **Method 1**: `chipo[chipo['item_price'] == chipo['item_price'].max()]`
  - More intuitive for beginners
  - Returns multiple rows if there are ties
  
- **Method 2**: `chipo.loc[chipo['item_price'].idxmax()]`
  - More efficient (only one comparison)
  - Returns only the first row if there are ties
  - Preferred in professional code

**Related methods:**
- `.idxmin()` for finding the index of the minimum value
- `.idxmax()` and `.idxmin()` are useful when you need the location, not just the value

In [14]:
chipo.loc[chipo['item_price'].idxmax()]

,quantity,item_name,choice_description,item_price,item_price_unit
order_id,,,,,
1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95
1443,7,Bottled Water,NaN,10.50,1.50
1443,1,6 Pack Soft Drink,[Coke],6.49,6.49
1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75,11.25
1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00,8.75
1443,3,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",27.75,9.25
1443,2,Bottled Water,NaN,3.00,1.50


**Expected Output:**
```
quantity                                     15
item_name             Chips and Fresh Tomato Salsa
choice_description                          NaN
item_price                                44.25
item_price_unit                            2.95
Name: 1443, dtype: object
```

Same result as Method 1, but displayed as a Series instead of a DataFrame row.

---
## Advanced Filtering and Counting

### Step 11. What was the quantity of the most expensive item ordered?

**Approach 1: Chain filtering and value extraction**

**Explanation:**  
This is a **three-step process** chained together:

1. **`chipo[chipo['item_price'] == chipo['item_price'].max()]`**:
   - Filters to get the row(s) with the maximum price
   - Returns a DataFrame (even if it's just one row)

2. **`['quantity']`**:
   - Selects just the 'quantity' column from the filtered DataFrame
   - Returns a Series

3. **`.values[0]`**:
   - `.values` converts the Series to a numpy array
   - `[0]` gets the first (and in this case, only) element
   - Returns a single integer value

**Why `.values[0]`?**  
Without it, we'd get a Series. With it, we get just the number we want.

In [23]:
chipo[chipo['item_price'] == chipo['item_price'].max()]['quantity'].values[0]

np.int64(15)

**Expected Output:**
```
15
```

**Alternative view: Without `.values[0]`**

**Explanation:**  
Let's see what we get if we stop before extracting the single value.

This returns a pandas **Series** showing:
- The index label (order_id = 1443)
- The column name (quantity)
- The value (15)
- The data type (int64)

**Difference:**  
- With `.values[0]`: Returns `15` (just the number)
- Without it: Returns a Series with metadata

**Which to use?**  
- If you need just the number for calculations → use `.values[0]`
- If you want to see the context (which order_id, etc.) → don't use `.values[0]`

In [16]:
chipo[chipo['item_price'] == chipo['item_price'].max()]['quantity']

order_id
1443    15
Name: quantity, dtype: int64

**Expected Output:**
```
order_id
1443    15
Name: quantity, dtype: int64
```

**See the complete row**

**Explanation:**  
This shows the **entire row** for the most expensive order, giving us full context.

**Benefits of seeing the full row:**
- We can see what item it was (Chips and Fresh Tomato Salsa)
- We see the quantity (15)
- We see the total price ($44.25)
- We see the unit price ($2.95 each)

This is more informative than just getting the quantity number alone.

In [17]:
chipo[chipo['item_price'] == chipo['item_price'].max()]

,quantity,item_name,choice_description,item_price,item_price_unit
order_id,,,,,
1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95


**Expected Output:**
```
          quantity                     item_name choice_description  item_price  \
order_id                                                                          
1443            15  Chips and Fresh Tomato Salsa                NaN       44.25   

          item_price_unit  
order_id                   
1443                 2.95  
```

### Step 11 (Alternative). Using idxmax with .loc

**Approach 2: Using idxmax() with .loc[]**

**Explanation:**  
This is an alternative approach that uses `.idxmax()` to find the index and then `.loc[]` to access specific data.

**Breaking down the code:**

1. **`chipo['item_price'].idxmax()`**:
   - Finds the index (order_id) with the maximum price
   - Returns: 1443

2. **`chipo.loc[1443, 'quantity']`**:
   - Uses `.loc[]` to access a specific cell
   - Row: 1443 (the index from idxmax)
   - Column: 'quantity'
   - Returns the quantity value at that location

**Important observation:**  
This example shows that `.loc[]` with a single index that appears multiple times (order_id 1443 has multiple items) will return **all rows** with that index, not just one.

**Result:**  
Returns a Series with all quantities from order 1443:
- 15 (Chips and Fresh Tomato Salsa - the expensive one)
- 7 (another item)
- 1, 3, 4, 3, 2 (other items in the same order)

**Key learning:**  
This demonstrates that order_id 1443 was a **large order with multiple items**, and the $44.25 chips were just one part of it!

In [18]:
chipo.loc[chipo['item_price'].idxmax(), 'quantity']

order_id
1443    15
1443     7
1443     1
1443     3
1443     4
1443     3
1443     2
Name: quantity, dtype: int64

**Expected Output:**
```
order_id
1443    15
1443     7
1443     1
1443     3
1443     4
1443     3
1443     2
Name: quantity, dtype: int64
```

**Analysis:**  
Order 1443 had 7 different items with various quantities. The 15 Chips and Fresh Tomato Salsa was the most expensive line item in this large order.

---
## Counting Specific Items

### Step 12. How many times was a Veggie Salad Bowl ordered?

**Explanation:**  
This combines **filtering** and **counting** to answer the question.

**Breaking down the code:**

1. **`chipo['item_name'] == 'Veggie Salad Bowl'`**:
   - Creates a boolean mask (True/False for each row)
   - True where item_name is exactly 'Veggie Salad Bowl'

2. **`chipo[...]`**:
   - Filters the DataFrame to keep only Veggie Salad Bowl rows

3. **`.count()`**:
   - Counts non-null values in each column of the filtered DataFrame
   - Returns the count for all columns

**Important note:**  
`.count()` counts non-null values. All counts should be the same (18) because we're counting complete rows.

**Alternative approaches:**
- `len(chipo[chipo['item_name'] == 'Veggie Salad Bowl'])` → Returns just the number 18
- `chipo[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]` → Also returns 18

**Result interpretation:**  
Veggie Salad Bowl was ordered **18 times** throughout the dataset.

In [19]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl'].count()

quantity              18
item_name             18
choice_description    18
item_price            18
item_price_unit       18
dtype: int64

**Expected Output:**
```
quantity              18
item_name             18
choice_description    18
item_price            18
item_price_unit       18
dtype: int64
```

All columns show 18, confirming there are 18 complete orders of Veggie Salad Bowl.

---
## Multiple Conditions

### Step 13. How many times did someone order more than one Canned Soda?

**Explanation:**  
This uses **multiple conditions** with the AND operator (`&`) to filter data.

**Breaking down the code:**

1. **`chipo['item_name'] == 'Canned Soda'`**:
   - First condition: item must be 'Canned Soda'

2. **`chipo['quantity'] > 1`**:
   - Second condition: quantity must be greater than 1

3. **`&`** operator:
   - Combines conditions with AND logic
   - Both conditions must be True
   - **Important:** Parentheses are required around each condition when using `&`

4. **`len()`**:
   - Counts the number of rows that meet both conditions

**Logical operators in pandas:**
- **`&`**: AND (both conditions must be True)
- **`|`**: OR (at least one condition must be True)
- **`~`**: NOT (inverts True/False)

**Common mistake:**  
Don't use Python's `and`/`or` keywords - use `&`/`|` operators instead for pandas.

**Result interpretation:**  
There were **20 instances** where someone ordered multiple Canned Sodas in a single line item.

In [20]:
len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)])

20

**Expected Output:**
```
20
```

**Alternative Method 1: Using .shape[0]**

**Explanation:**  
`.shape` is an attribute that returns the dimensions of the DataFrame as a tuple: `(rows, columns)`

**Breaking down `.shape[0]`:**
- `.shape` returns something like `(20, 5)` meaning 20 rows and 5 columns
- `[0]` gets the first element of the tuple → the number of rows
- This is equivalent to `len()` but more explicit about getting row count

**When to use:**
- `.shape[0]` is clearer when you explicitly want the row count
- `len()` is more concise and commonly used
- Both give the same result

**Note:**  
`.shape[1]` would give you the number of columns (5 in this case).

In [21]:
chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].shape[0]

20

**Expected Output:**
```
20
```

Same result as using `len()` - confirming 20 orders.

**Alternative Method 2: Using .count()**

**Explanation:**  
`.count()` returns the count of non-null values in each column.

**What you'll see:**
- All columns show the same count (20) because we're counting complete rows
- Returns a Series with counts for each column

**Comparison of the three methods:**

1. **`len(filtered_dataframe)`**:
   - Returns: Single integer (20)
   - Pros: Simple, concise, fast
   - Best for: When you just need the count

2. **`.shape[0]`**:
   - Returns: Single integer (20)
   - Pros: Explicit about getting row count
   - Best for: Code clarity, when working with dimensions

3. **`.count()`**:
   - Returns: Series with count per column
   - Pros: Shows if any columns have missing data
   - Best for: Data quality checks, seeing column-by-column counts

**Best practice:**  
For simple "how many rows" questions, use `len()` or `.shape[0]`.

In [22]:
chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].count()

quantity              20
item_name             20
choice_description    20
item_price            20
item_price_unit       20
dtype: int64

**Expected Output:**
```
quantity              20
item_name             20
choice_description    20
item_price            20
item_price_unit       20
dtype: int64
```

All columns show 20, confirming 20 orders met both conditions.

---
## Summary: Key Concepts Learned

### Data Loading and Preparation
- Reading TSV files with `pd.read_csv(sep='\t')`
- Setting index columns with `index_col`
- Converting data types (string to float)
- Creating calculated columns

### Exploring Data
- `.head()` and `.tail()` for quick inspection
- `.info()` for DataFrame structure
- `.unique()` for distinct values
- `.nunique()` for counting unique values

### Filtering Data
- Boolean indexing: `df[condition]`
- Multiple conditions with `&` (AND) and `|` (OR)
- Finding maximum/minimum with `.max()`, `.min()`
- Finding index of max/min with `.idxmax()`, `.idxmin()`

### Counting Methods
- `len(df)` - total rows
- `.count()` - non-null values per column
- `.shape[0]` - number of rows explicitly

### Sorting
- `.sort_values(by='column')` for organizing data

### Best Practices
1. **Always inspect your data** with `.head()`, `.info()` before analysis
2. **Convert data types** when necessary (like removing '$' from prices)
3. **Use descriptive variable names** (chipo, not df)
4. **Choose the right counting method** based on your needs
5. **Use parentheses** when combining conditions with `&` or `|`
6. **Verify your results** using multiple methods when learning

### Common Patterns
```python
# Filter and count
df[df['column'] == value].count()

# Multiple conditions
df[(condition1) & (condition2)]

# Find max/min row
df.loc[df['column'].idxmax()]

# Extract single value
df[condition]['column'].values[0]
```

**Remember:** There are often multiple ways to accomplish the same task in pandas. Choose the method that is most readable and efficient for your specific use case!